import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Flex } from "@chakra-ui/react";
import useMediaQuery from "../src/hooks/useMediaQuery";
import People from "../src/features/People";
import Tweets from "../src/features/Tweets";
import Header from "../src/flat/Header";
import styles from "../styles/Home.module.css";
import axios from "axios";

interface HomeProps {
  tweets: any[];
  people: any[];
  meta: any;
}

const Home = ({ tweets, meta, people }: HomeProps) => {
  const isMobile = useMediaQuery("(max-width: 768px)");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex w="100%" justifyContent="center" alignItems="center">
        <Flex w="100%" justifyContent="center">
          {!isMobile && <People people={people} />}
          <Flex flexFlow="column" maxW="500" w="100%">
            <Header />
            <Tweets initialTweets={tweets} meta={meta} />
          </Flex>
        </Flex>
      </Flex>
    </div>
  );
};

// This function gets called at build time
export async function getStaticProps() {
  let response = await axios.get(
    `https://api.twitter.com/2/tweets/search/recent?query=%23${process.env.HASHTAG}&expansions=author_id`,
    {
      headers: {
        Authorization: `Bearer ${process.env.TWITTER_BEARER_TOKEN}`,
      },
    }
  );

  let responsePeople = await axios.get(
    `https://api.twitter.com/2/users?ids=${response.data.data
      .map((tweet: any) => tweet.author_id)
      .join()}&user.fields=profile_image_url,username`,
    {
      headers: {
        Authorization: `Bearer ${process.env.TWITTER_BEARER_TOKEN}`,
      },
    }
  );

  const uniquePeople = [
    ...new Map(
      responsePeople.data.data.map((person: any) => [person.id, person])
    ).values(),
  ];

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      tweets: response.data.data,
      meta: response.data.meta,
      people: uniquePeople,
    },
  };
}

export default Home;
