import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { Flex } from "@chakra-ui/react";
import Tweets from "../src/features/Tweets";
import Header from "../src/flat/Header";
import styles from "../styles/Home.module.css";
import axios from "axios";

interface HomeProps {
  tweets: any[];
}

const Home = ({ tweets }: HomeProps) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex w="100%" justifyContent="center" alignItems="center">
        <Flex flexFlow="column" maxW="500" w="100%">
          <Header />
          <Tweets tweets={tweets} />
        </Flex>
      </Flex>
    </div>
  );
};

// This function gets called at build time
export async function getStaticProps() {
  let response = await axios.get(
    "https://api.twitter.com/2/tweets/search/recent?query=%23buildinpublic",
    {
      headers: {
        Authorization: `Bearer ${process.env.TWITTER_BEARER_TOKEN}`,
      },
    }
  );

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      tweets: response.data.data,
    },
  };
}

export default Home;
